version: 1.0 # Do not change this; it may break updates.
database:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:{DIR}{NAME}.db
  username: root
  password: walrus
  isolation: SERIALIZABLE
  logging: false
import_export_path: plugins\DynamicMarket\ # Location of shops.csv.
transaction_logging: true # Logs transactions in the database table "transactions".